2024-12-09 15:51:45,254 - INFO - 
Available Models:
2024-12-09 15:51:45,255 - INFO - - random_forest: A random forest model
2024-12-09 15:51:45,255 - INFO - - decision_tree: Decision tree classifier optimized for medical data analysis
2024-12-09 15:51:45,255 - INFO - - hist_gradient_boosting: A histogram gradient boosting model
2024-12-09 15:51:45,255 - INFO - - bagging: A bagging model
2024-12-09 15:51:45,255 - INFO - 
Starting experiments...
2024-12-09 15:51:45,255 - INFO - 
Starting experiment with random_forest
2024-12-09 15:52:05,046 - INFO - Completed experiment with random_forest
2024-12-09 15:52:05,046 - INFO - 
Starting experiment with decision_tree
2024-12-09 15:55:14,048 - INFO - Completed experiment with decision_tree
2024-12-09 15:55:14,048 - INFO - 
Starting experiment with hist_gradient_boosting
2024-12-09 15:58:29,659 - INFO - Completed experiment with hist_gradient_boosting
2024-12-09 15:58:29,659 - INFO - 
Starting experiment with bagging
2024-12-09 16:26:09,393 - ERROR - Error in bagging experiment: Error creating SHAP explainer: Unsupported model type: BaggingClassifier
Traceback (most recent call last):
  File "/nfs/home/jimjak/Master-Thesis/src/evaluation/model_evaluator.py", line 242, in _create_explainer
    raise ValueError(f"Unsupported model type: {model_name}")
ValueError: Unsupported model type: BaggingClassifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/jimjak/Master-Thesis/src/models/experiment_suite.py", line 52, in run_experiments
    experiment.run()
  File "/nfs/home/jimjak/Master-Thesis/src/experiment/experiment.py", line 142, in run
    aggregated_shap, feature_importance_dataframe, feature_importance_abs_mean = self.evaluator.calculate_feature_importance(
  File "/nfs/home/jimjak/Master-Thesis/src/evaluation/model_evaluator.py", line 123, in calculate_feature_importance
    self.explainer = self._create_explainer(best_model, X_test_transformed)
  File "/nfs/home/jimjak/Master-Thesis/src/evaluation/model_evaluator.py", line 244, in _create_explainer
    raise Exception(f"Error creating SHAP explainer: {str(e)}")
Exception: Error creating SHAP explainer: Unsupported model type: BaggingClassifier
2024-12-09 16:26:09,395 - INFO - All experiments completed successfully
2024-12-09 16:26:09,395 - INFO - 
Results and log file saved in: outputs/20241209_155145
